  $(document).on('click','button', function(){
                              var id= $(this).attr('id');
                          
                              if (id == 'Botelho'){
                                 $('.portfolio-content').html("<img src='images/individual/Roberto_Botelho2.jpg' alt='Roberto Botelho'> <h3>About Me</h3> <p>Originally from the Azores, <a  href='https://en.wikipedia.org/wiki/Portugal'> Portugal</a>, I have been a Torontonian since 1989! I did my B.Sc. at York University, Ph.D. at the University of Toronto in the Dept. of Biochemistry under the supervision of <a  href='http://biochemistry.utoronto.ca/person/sergio-grinstein/'>Dr. Sergio Grinstein</a> at Sick Kids. I followed my graduate studies with a post-doctoral fellowship in <a  href='https://emr.wicmb.cornell.edu/'> Dr. Scott Emr’s lab </a>, first at University of <a href='https://en.wikipedia.org/wiki/San_Diego' target='_blank'> California San Diego </a> and then in <a href='https://www.cornell.edu/' target='_blank'>Cornell University </a>. </p><h3> Research Interest </h3> <p> I have been a Professor at Ryerson University since 2008 teaching cell biology-related topics and I lead a research lab that investigates a variety of topics including innate immune cells, phagosome maturation in macrophages, lysosome function and regulation, and phosphoinositide signalling, all under the umbrella of organelle identity and function. </p><h3> Fun Facts </h3> <p>Chances are that if you come see me, I’m listening to drum n’ bass, Dubstep, house (dark is better), Downtempo and sometimes classical.</p><i class='fa fa-linkedin-square' aria-hidden='true'></i>").fadeIn();
                              }
                              else if (id == 'Chris'){
                                 $('.portfolio-content').html('<img src="images/individual/Christopher Choy.jpg" alt="Christopher Choy"><h3> Research Interest </h3><p> I am a senior Ph.D. student and alumni of Ryerson. I aim to understand how cells can control biosynthesis of lysosomes through modulating phosphoinositide lipids and through phagocytosis. We want to find specific molecular switches that can control the transcription factor EB, which researchers have identified as a potential therapeutic target. </p><h3> Fun Facts </h3><p> I have never watched my boss’s favourite shows, The Walking Dead or Game of Thrones </p> <a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>').fadeIn();
                              }
                              else if (id == 'Golam'){
                                 $('.portfolio-content').html('<img src="images/individual/Golam.JPG" alt="Golam Saffi"><h3>About Me</h3><p>I completed my BSc and MSc at the University of Waterloo and currently seeking a PhD in the Botelho lab.</p><h3> Research Interest </h3> <p> PIKfyve is a lipid kinase that generates the late endosome-lysosome (endolysosome) membrane lipid PI3,5P2. However, depletion of PI3,5P2 results in dramatic enlargement of endolysosomes. My research aims at identifying chemicals and protein factors that regulate such enlargement and endolysosome dynamic in general.</p><h3> Fun Facts </h3> <p> I like to have a multidimensional mind that can contemplate multiple visionaries at the same time including science, philosophy (from Islam), family and somewhat comedy (although I may not be that funny to some. Har har!!). Also, I like playing video games.</p><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>').fadeIn();
                              } 
                              else if (id == 'Yasmine'){
                                 $('.portfolio-content').html('<img src="images/individual/Yasmine.jpg" alt="Golam Saffi"><h3> Research Interest </h3> <p> My undergraduate was completed at Ryerson University in Biology. My project is about determining whether LYCAT (lysocardiolipin acyltransferase) is involved in the resynthesis and quality control of the types of fatty acids that are attached to phosphoinositides. This is important because phosphoinositides like phosphatidylinositol-4,5-bisphosphate, whcih is found on the plasma membrane, is depleted during signaling. </p><h3> Fun Facts </h3> <p>  I was not allowed to watch the Simpsons until I was 19 years old.  My favourite Disney movie is Mulan.  And I am the eldest in the family but I am only 5 feet 2. </p><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>').fadeIn();
                              } 
                              else if (id == 'Louis'){
                                 $('.portfolio-content').html(" <img src='images/individual/Louis Lo.jpg' alt='Louis'> <h3> Research Interest </h3><p> I am a M.Sc. student candidate co-supervised by Drs. Botelho and Antonescu in the Dept. of Chemistry and Biology and by Dr. Raffi Kasharfian in Physics. I completed my BSc at Ryerson in biology and continued my research into graduate studies. My research focuses on the effects of ultrasound in combination with microbubbles on the diverse stress response pathways of a cell. I want to understand how this specialized technique can help improve and support cancer therapies.</p><h3> Fun Facts </h3><p> you’ll probably find me at the Mattamy Athletic Centre gym taking pictures of myself for my snapchat. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                              else if (id == 'Victoria'){
                                 $('.portfolio-content').html(" <img src='images/individual/Victoria.jpg' alt='Victoria'> <h3> Research Interest </h3><p> I am a senior PhD student in the Botelho Lab. I completed my undergrad here at Ryerson University. My research is focused on understanding how immune cells adapt their lysosomes in response to infection. We want to understand how lysosomal adaptation helps our immune cells boost immunity. </p><h3> Fun Facts </h3><p> I enjoy educating and translating science to the public. </p><a  href='https://www.linkedin.com/in/victoria-hipolito'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();     
               
                              }
                              else if (id == 'Aaron'){
                                 $('.portfolio-content').html("<img src='images/individual/Aaron.jpg' alt='Aaron'><h3> About Me </h3><p> I am a Masters student in Molecular Science. My undergraduate was at Queen's University at Kingston.</p><h3> Research Interest </h3><p> My work focuses on phagosome resolution, or how a phagocyte, such as a macrophage, resets phagocytosis in order to intake particles again. Our working model is that phagolysosomes in mammalian cells fragment and reform into lysosomes, instead of ejecting its contents out of the cell. </p><h3> Fun Facts </h3><p> I built a boat with a duct tape hull with some of my friends in Scouts. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();
                              }
                              else if (id == 'Jacqueline'){
                                 $('.portfolio-content').html("<img src='images/individual/Jacqueline.png' alt='Jacqueline'><h3> Research Interest </h3><p> I am a third-year undergraduate student in the Biomedical Science program. My project is focused on immune cells, specifically macrophages, and their lysosomes. We want to understand how macrophages remodel their lysosomes upon exposure to infection and how this may help to facilitate clearance by the immune system.</p><h3> Fun Facts </h3><p> about myself: I love to draw... but I’m pretty terrible at it. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();
                              }
                              else if (id == 'Subo'){
                                 $('.portfolio-content').html(" <img src='images/individual/Subo.jpg' alt='Subo'><h3> About Me </h3><p> I am a MSc student in the Botelho lab. I did my undergraduate degree at the University of Toronto majoring in microbiology and health & disease. There, I studied virus-host interactions of enteric adenovirus in Dr. Martha Brown’s lab. </p><h3> Research Interest </h3><p> My current research is focused on elucidating the role of the transcription factor EB (TFEB) in lysosomal physiology in macrophages. Ultimately, we want to see if TFEB is an important factor in immune responses against bacterial pathogens. My research uses both in vitro and in vivo models to study TFEB. </p><h3> Fun Facts </h3><p> I am dragon boat paddler (5 years and counting) and you can always find me at the gym working hard (slowly) towards a 315 lbs squat. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();
                                 
                              }
                              else if (id == 'Saba'){
                                 $('.portfolio-content').html("<img src='images/individual/Saba.jpeg' alt='Saba'><h3> Research Interest </h3><p> I am an undergraduate research assistant in my 3rd year in the biomedical science program. My project aims to understand how proteins such as acyltransferases control and mediate signalling pathways, and their impact on the physiology of the cell. </p><h3> Fun Facts </h3><p>I read somewhere that chocolate is going to run out by the year 2050, and that’s the excuse I use for eating so much chocolate. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();
                                 
                              }
                              else if (id == 'Janusan'){
                                 $('.portfolio-content').html(" <img src='images/individual/Janusan Baskararajah.JPG' alt='Janusan'><h3> Research Interest </h3><p> I’m a Biomedical Science undergraduate thesis student. My project involves studying free radical activity on lysosomal dynamics through use of reactive oxygen producing species such as rotenone and H2O2.</p><h3> Research Interest </h3><h3> Fun Facts </h3><p> I am as good at reciting the alphabet backwards as I am forwards.</p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();
                                 
                              }
                               else if (id == 'Eliot'){
                                 $('.portfolio-content').html(" <img src='images/individual/eliot.jpg' alt='eliot'><h3> Research Interest </h3><p> I am an undergraduate student in my 3rd year at Ryerson on course to graduate in 2019 with a Bachelors of Science. I have a large interest in the field of cellular biology and organelle functions. My work is based on membrane trafficking during endocytosis and its relations to lysosomal uptake and regulation. In my group, we want to study the overall quantitative and qualitative analysis of lysosomes before and after phagocytosis. </p><h3> Fun Facts </h3><p>  I am I huge fan of football and root for the Los Angeles Chargers! </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                              else if (id == 'Emily'){
                                 $('.portfolio-content').html(" <img src='images/individual/Emily.png' alt='Emily'><h3> Research Interest </h3><p> I am an undergraduate student in my 3rd year. My project aims to develop a system for studying lysosome fission using sucrose, which causes lysosomes to become enlarged – these are known as sucrosomes. The lysosome is an organelle that is vital for proper cell function, and lysosome fission is a process that is not yet well-characterized. </p><h3> Fun Facts </h3><p> I love cooking, sports, and rock music.</p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                              else if (id == 'Neha'){
                                 $('.portfolio-content').html(" <img src='images/individual/Neha.jpg' alt='Neha'><h3> Research Interest </h3><p>  I am a fourth-year undergraduate thesis student in the Botelho lab. My project focuses on characterizing the effects of vaccine adjuvants on lysosomal remodeling and antigen presentation within primary immune cells. </p><h3> Fun Facts </h3><p> aside from studying lysosomal tubulation, I am also a professional Netflix binge watcher. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                              else if (id == 'Yeonjoon Kim'){
                                 $('.portfolio-content').html(" <img src='images/individual/Yeonjoon Kim.jpg' alt='Yeonjoon Kim'><h3> Research Interest </h3><p> I’m an undergraduate thesis student. My project is studying how TFEB (Transcription Factor EB) responds to invading particles under the inhibition of a kinase known as class I PI3K (phosphatidylinositide 3-kinase) </p><h3> Fun Facts </h3><p>  I’m usually in a good mood but it never shows on my face. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                              else if (id == 'Vanessa Jacobelli'){
                                 $('.portfolio-content').html(" <img src='images/individual/Vanessa Jacobelli.jpg' alt='Venessa'><h3> Research Interest </h3><p> I am an undergraduate student in my 3rd year at Ryerson. My work focuses on phagolysosome fragmentation and lysosome renewal. We want to study how lysosomes change as bacteria is taken up and degraded. </p><h3> Fun Facts </h3><p> I used to dance competitively. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();                  
                              } 
                               else if (id == 'Ahmad Sidiqi'){
                                 $('.portfolio-content').html(" <img src='images/individual/Ahmad.jpg' alt='Venessa'><h3> About Me </h3><p> I had the pleasure of being supervised by Dr. Botelho as an Undergraduate Research Opportunity, and an NSERC USRA student for three summers. I continued my project, which focused on Vac14 modulating Fig4 activity, for my 4th year undergraduate thesis. Dr. Botelho is an incredibly patient and innovative supervisor who is passionate for teaching his students research and interpersonal skills. He trusts his students and builds their confidence and independence -- both of which have been invaluable to me throughout my academic career. The experience I gained was crucial for my successful completion of my M.Sc. at the University of Toronto and St. Michael’s Hospital, and has continued to help me as a medical student at the University of British Columbia. <h3> Fun Fact </h3> <p> I have an energetic little nephew! </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();            
                              } 
                              else if (id == 'Antonietta'){
                                $('.portfolio-content').html(" <img src='images/individual/Antonietta.png' alt='Venessa'><h3> About Me </h3><p> I was a undergraduate thesis student inn the Botelho lab, where I helped explore protein interactions between PIP phosphates, kinases and associated scaffolding proteins in the yeast secretory system. I’m currently a Ph.D candidate at the Atlantic Research Centre at Dalhousie University, studying a cholesterol and PIP binding/transport protein called ORP4 under the guidance of Dr. Neale Ridgway. The Botelho lab was my first introduction to just how cool it is that organelles maintain their identity while constantly swapping cargo. Now I’ve caught the bug and want to spend my career studying membrane lipids and intracellular trafficking. <h3> Fun Fact </h3> <p> learned many things in the Botelho lab, the most important of which might have been that overnight transfers should not be run at 100 V. </p><a  href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();          
                              } 
                               else if (id=='Monica Dayam'){$('.portfolio-content').html(" <img src='images/individual/alumni/monica.jpg' alt='Monica'><h3> About Me </h3><p> I worked with Dr. Botelho’s lab from 2010-2013 during my Bachelor of Science inBiology, first as NSERC USRA and then as thesis student. This was followed by myPh.D. in Molecular Science in 2013-2017, where I investigated “Role of PIKfyve inmacrophages and neutrophils immune response”. Now, I am Postdoctoral fellow atHarvard Medical School (Department of Cell Biology) and Boston Children&#39;s Hospital(Program in Cellular and Molecular Medicine). The research and training grounds atthe Botelho’s lab enhanced my intellectual, communication, leadership, and researchskills, which advanced my long-term goal of being a researcher in the health science. </p><h3> Fun Fact </h3> <p> Oh, dear Lord...there are way too many... </p><a href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();}
                              else if (id=='Amra Saric'){$('.portfolio-content').html(" <img src='images/individual/alumni/Amra Saric.jpg' alt='Monica'><h3> About Me </h3><p> I conducted my PhD in Molecular Science in the Botelho laboratory at RyersonUniversity, elucidating the mechanisms of lysosome tubulation in innate immunecells. Prior to graduate school, I received my BSc in Chemistry and Biology atRyerson, during which time I first learned of the exciting work in the Botelho lab, asI conducted an 8-month undergraduate thesis project under the supervision of Dr.Roberto Botelho. I am currently a postdoctoral research fellow in the laboratory ofDr. Juan S. Bonifacino at the National Institutes of Health (NIH/NICHD) in Bethesda,MD, where I study the role of organelle positioning in health and disease. Theresearch topics, curriculum structure and supervision I received in the Botelho labhas empowered me to pursue my research interests at the highly reputable lab andinstitute that I am currently a part of.</p><h3> Fun Fact </h3> <p> I am a huge fan of sci-fi/fantasy books and films including Dune, Lordof the Rings, Game of Thrones, Star Wars, Harry Potter</p><a href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();}
                               else if (id=='Leslie Bone'){$('.portfolio-content').html(" <img src='images/individual/alumni/Leslie.jpg' alt='Monica'><h3> About Me </h3><p> I was a PhD student in the Botelho lab, co-supervised with Dr. Costin Antonescu. Istudied the function of an acyltransferase, LYCAT, responsible for the enrichment ofphosphoinositides with stearic acid. I now work as a Business Development Specialist forMITACS, a national not-for- profit research organization that offers training and researchprograms that will develop the next generation of researchers and innovators in Canada. </p><a href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();}
                            else if (id=='Tamadher Alghamdi'){$('.portfolio-content').html(" <img src='images/individual/alumni/Tamadher.jpg' alt='Monica'><h3> About Me </h3><p> I joined Dr. Botelho’s lab as a master&#39;s student in the Molecular Science program atRyerson University.  My master&#39;s thesis research focused on functional characterizationof the Vac14 self-interaction domain. This work has enabled characterization of theVac14 multimer as a crucial regulator of phosphatidylinositol-3,5- bisphosphate[PtdIns(3,5)P2], a signaling lipid essential for lysosomal function and implicated inneuropathological diseases such as Amyelotrophic Lateral Sclerosis. The findings of thisstudy, in combination with that of my former research group, have been published in theJournal of Biological Chemistry. I am now a PhD candidate in the Institute of MedicalScience at the University of Toronto and I am conducting my research at St. Michael&#39;sHospital. My time in Dr. Botelho’s lab has given me a greater appreciation forfundamental research and prepared me very well to continue my postgraduate studies.</p><h3> Fun Fact </h3> <p> I am multilingual and I love travelling.</p><a href='#'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();}
                            else if (id=='Krishna Chintaluri'){$('.portfolio-content').html(" <img src='images/individual/alumni/Krishna.jpeg' alt='Monica'><h3> About Me </h3><p> I recently graduated with a Master’s in Molecular Science from the Botelho Lab. My projectfocused on researching novel probes for endosomal phosphoinositides. This ties into thebroader focus of lab in our study of the endolysosomal system.</p><h3> Fun Fact </h3> <p> When I’m notthinking about science, I think about what it would be like owning a professional sports team. </p><a href='www.linkedin.com/in/krishna-chintaluri'><i class='fa fa-linkedin-square' aria-hidden='true'></i></a>").fadeIn();}
                           });
